Login dev issues 2
frg-fossee/eSim-Cloud pull request #357
Opened 2021-08-09 10:57 UTC by asif986

1 when logout user into arduino then Esim automatic logged . this issuess fixed.

2021-08-10 17:16 UTC, kumanik5661 approved these changes
Other things seem fine

2021-08-10 17:16 UTC, kumanik5661 commented on eda-frontend/src/redux/actions/authActions.js
> +            window.location.href = toUrl+"?token=" + localStorage.getItem('esim_token');
Maybe a security concern? 
Normally I wouldn't want to expose the token like this via the URL

2021-08-10 17:16 UTC, kumanik5661 commented on eda-frontend/src/redux/actions/authActions.js
> +        },
Extra comma might interfere(?)

2021-08-10 17:17 UTC, kumanik5661 requested changes
Other things seem fine

2021-08-11 12:06 UTC, asif986 commented on eda-frontend/src/redux/actions/authActions.js
> +        },
Ok . I can remove.

2021-08-16 17:04 UTC, merged